### ISSUE TITLE
Menu Item '0' is unusable 

### ISSUE THREAD

**Issue by R00Ki3** [fortressforever/fortressforever#140]
The menu selection that's used for Lua and Source mod Won't allow you to use '0'  if its an option on the menu. Notice how zero is whited out. In some source mod plugins zero is the exit button. Which makes this issue a bit annoying.

![ff_lua_test0002](https://cloud.githubusercontent.com/assets/3948413/6812801/2cb884d0-d23f-11e4-8e9f-77e04a0dafa3.jpg)

**Comment by squeek502** [comment]
Can you post the Lua code you're using to create/show the menu? Too lazy to write it myself. :smile:

**Comment by R00Ki3** [comment]
``` lua
            CreateMenu( "skin_menu", "Ball Skin", 30 )
            AddMenuOption( "skin_menu", 1, "item 1" )
            AddMenuOption( "skin_menu", 2, "item 2" )
            AddMenuOption( "skin_menu", 3, "item 3" )
            AddMenuOption( "skin_menu", 4, "item 4" )
            AddMenuOption( "skin_menu", 5, "item 5" )
            AddMenuOption( "skin_menu", 6, "item 6" )
            AddMenuOption( "skin_menu", 7, "item 7" )
            AddMenuOption( "skin_menu", 8, "item 8" )
            AddMenuOption( "skin_menu", 9, "item 9" )
            AddMenuOption( "skin_menu", 0, "<- Notice the color" )
            ShowMenuToPlayer( player, "skin_menu" )
```

**Comment by squeek502** [comment]
As far as I can tell, this is all working properly. Are you sure you have your 0 bound correctly? It should be bound to `slot10`, which gets sent to the server as the command `menuselect 10`, which [gets translated to 0 here](https://github.com/fortressforever/fortressforever/blob/beta/game_shared/ff/ff_gamerules.cpp#L1182-L1183).

The following code:

```
function player_onmenuselect(player, menu_name, slot)
    print(tostring(player).." selected slot "..tostring(slot).." of "..menu_name)
end
```

gives:
`player:squeek.:1 selected slot 0 of skin_menu`

As for the different color, that seems to be [an intended special case for the `0` option](https://github.com/fortressforever/fortressforever/blob/beta/cl_dll/menu.cpp#L198) that hasn't been changed since [the inital SDK import commit in 2006](https://github.com/fortressforever/fortressforever/blame/beta/cl_dll/menu.cpp#L198).

Closing for now. Re-open if the color thing is a problem.

**Comment by R00Ki3** [comment]
Thanks for the clarification, it seems my '0' was bound to slot0 instead of slot10 for some reason.
