### ISSUE TITLE
Managed to fly right through the flag

### ISSUE THREAD

**Issue by ProjectMoon** [fortressforever/fortressforever#154]
Not sure how this happened.

It was on Palermo.

I rocket+grenade jumped and slid up the roof above CP 2. The flag was on the roof. I went right through it, from both my perspective and Headzy's. Unfortunately, I have no demo. It might be related to the smaller flag radius? Or maybe I just did actually miss it.

It could be worth investigating at least a little bit. The key components:
- High speed
- Sliding up ramp
- Flag on ramp

Also, the angle of the CP2 roof on Palermo is quite steep.

**Comment by R00Ki3** [comment]
Thanks for your input, the flag's height is slightly shorter than the actual model. it might feel as you're going through it but its working as intended (might change in the future?).  Players don't have hands on their feet so their feet shouldn't be able to grab the flag.

**Comment by squeek502** [comment]
Were you on the ground or in the air while you went through it?

**Comment by fpsmoto** [comment]
R00ki3, the pole in which the flag is attached to is as tall as the actual model of the flag. Also, if the argument is that you're hands aren't low enough to grab a flag that's on a lower surface, then what about while you are crouching? Your hands can reach below your feet that way and that's why I think that argument is flawed. However, this game is nowhere near realistic, so the only way to find a solution is by testing what works and what doesn't and via community feedback, regardless of if it makes sense in the real world. From what I've seen in game since the Steam release, the majority of people I've played with do not like the flag changes, among other things. It might be too early to tell how this will affect gameplay overall, but I think the height should be increased to the height of the flag model.

**Comment by rawDawg216** [comment]
I agree with Moto 100%!  Please fix the flag! Pickups have suffered all weekend.  Going from 112% to 65% vertical bounds is a HUGE change.  You can now jump over the flag ffs!  Please consider something more reasonable and less drastic.  At least shrink the flag model to the same size as the new bounds so you can't conc right through the top of it.

**Comment by ProjectMoon** [comment]
I was in the air when going through it. I hit the very steep slope, and then slid up through it (from my perspective).

It's probably just easiest to revert the flag size change. It can be hard enough to grab the flag on some maps, especially with competent defense. What was the original reason for the change anyway?

**Comment by squeek502** [comment]
Not a bug. From the changelog:

> Flag touch bounds have been decreased somewhat significantly: touch height is now ~65% of flag height, and touch width is now ~100% of flag width (flag touch bounds used to be larger than the flag itself in both dimensions)

If you want to discuss the merits of the change, see #166.
