### ISSUE TITLE
Petition to change default server values for secondary grenades for Pyro class

### ISSUE THREAD

**Issue by fpsmoto** [fortressforever/fortressforever#238]
Should be 1 initial and 2 max. Currently, the default value is 4 max, 2 initial.

**Comment by woahjoe** [comment]
Disagree, it should be 3 initial 4 max. The pyro suffers a great deal without napalm grenades to get a quick level three burn going against heavy armor classes and sentry guns. Pyro gameplay/fun factor suffers a lot on maps (dustbowl, ksour, etc) that offer no secondary grenades on spawn.

**Comment by MaxRideWizardLord** [comment]
No No No and No. Pyro in current state is already suffers a lot at combat against heavy classes, especially HWguy and sentrygun. Napalm grenades are almost essential for the pyro's main combat\assassination role. And due to the fact that his primary weapon (flamethrower) deals not so good DPS that almost equals to supershotgun (flamethrower = 16hp dmg per 0.2 sec vs supershotgun = 54hp dmg per 0.7 sec) which is not high damage for close quarter primary weapon, pyro has to find other way around to deal with heavier classes that have much greater damage up close and mid-range, because even not so good soldier can give greater DPS by simple spamming rockets on floor, while RPG being mid-range weapon as well unlike flamethrower that is only effective at close range only.

Without those napalm nades, highly experienced pyro wouldn't have a chance to deal with equally highly experienced soldiers. Against really experienced soldiers, the best bet you have is to set them on level 2 using napalm nade and IC, then give extra damage with either 'pellet gun', IC to restore the timer of afterburn you caused to him which will do stable DOT damage and frag nade from safe distance. With the afterburn nerf, it become more troublematic to deal with more experienced soldiers than before, and it takes more time to finally finish them off than before and yet try to survive yourself and the rist that they will just kill you with supershotgun\pellet gun now is really higher. Risk your own life and rush them with flamethrower is bad idea, because no matter how good you're at dodging and tricking even by double jumping with flamethrower, a good soldier can predict all your future movement and land a rocket under your feet which will launch you in sky and make you defenceless free target that he sure could easily finish off; however, if it's really big open area yarding, then you could try to IC jump and puff him with flamethrower a few times to be sure it will hit him, let him feel 3 level burn and then just back pedal and run away in a hope to survive, but this won't always work and in most case will result to fail.

Pyro In more serious matches result to play more stealthy and ambush type of gameplay in order to set same HWguy with insane amount of DPS and ability to push pyro away with overpressure on level 3 must act quiet and prepare napalm nade before even attack with any of his weapons and then run away. With only 2 napalm nades that means a really good stealthy pyro could manage to kill only a two soldiers maximum (only if those soldiers are not near medkits, because after afterburn nerf they have a chance to survive, especially if they are at defence) in single run if he was lucky to took the nade pack from the spawn and not a fact he will hit with it as soldier may dodge it, which means he mostly was wasted in vain, so running with only one napalm nade would be really risky. Plus after afterburn nerf, the hwguy have high chance to survive pyro's rush against him, trying to use all his 3 weapons and damage him a bit, especially if hwguy is at defence near resuply with health\armour.

2 napalm nade max (1 initial) also means he has no chance to fight against sentrygun with proper engineer behind it. Sure he could spam all his frag nades, but a good engineer is able to save his sentry guy from those if they are a little away from the sentrygun itself and not just at point blank (a good engineer usually manages to save his sentrygun against 4 frag grenades droped near sentrygun, but that depends on both of amount of cells engineer have, distance of how futher the nades are from sentrygun and how good engineer at timing to take least damage from those grenades). Engineer is already like a hard counter of pyros, where he barely can do anything at all to ranged sentry with how low damage IC does, so it would be fair if he could at least able to do something serious to it and engineer upclose, not to mention that god damn EMP with no fallout damage over distance that instagib you with combination of single shot of supershotgun even if you drop the ammopack (eh, I really wish flamethrower could use bullets ammo type instead of cells. That could kill 3 birds in one shot, pyro could drop backpacks with cells to engineer for his buildings, EMP would do far less damage to pyro (maybe around like 50% of hp, like emp does to soldier, or maybe even less since he doesn't have that much of rockets) and pyro wouldn't just meaninglessly waste all his ammo of flamethrower and IC just to survive a fight against engineer, but that is a bit offtopic right here). To be honest, I do infact agree with woahjoe here, he would need more of those napalm nades than less to have a fair fight against sentryguns as offense pyro, or as defence pyro if you fight against offense hwguys\soldier, especially would be welcome on AVD maps like ff_napoli, ff_palermo, and CP maps like ff_warpath where he lack of destructive power. Not like that he needs to be as powerful as demoman, but at least to have chance to fight back against hwguys, soldiers and sentryguns. But instead of adding extra napalm nade to pyro, I rather wish developers fix all the flamethrower bugs that pyro have, especially fix that hit registry issue, and maybe tweak flamethrower a little to make it be more deadly to heavier classes and more viable against them.

Then again, pyro is a rare type of a class that request the pyro itself to participate in combat in order to make those nades be any useful, and sometimes laid all 3 different type of fire weapons to single enemy could be really hard up to impossible in certain situations, for example you couldn't hit them with flamethrower, or random sentry gun push you up, or soldier launch you up in the sky by shooting at floor with his rocket launcher (which happens really often when you try to catch on fire using flamethrower, so flame push becomes your worst enemy as you become easy target for supershotgun\rocket hits + fall damage), or even flamethrower get canceled by nail spam or any other projectile (not so known issue that been here for long) or any other circumstances. Those neither work like frag grenades, means you can't just use them from safe distance as extra damage output and hope for best outcome out of it even if it explode in the enemy's face. You can't just spam those and achieve instant level 3 afterburn like you could spam MIRV nades at sentry or laser nades at entrance door and forget about them; you'd still be forced to risk your own life and get close to enemy, combinating both weapons and nade to get desireble effect to work. Neither it's that easy as it looks, the splash radius of explosion of napalm nade is actually noticeably much smaller compared to normal frag nade which would add that extra afterburn level. Most of the time when you have ping above 80's, you'll happened to achieve level 3 afterburn attachment on enemy only by fooling the enemy to walk in to the that small burning 'area denial' area of effect damage which adds extra level afterburn, this is where 4 napalm nades would really be welcome as well, even if you not just mindlessly spam them around (which is awful idea anyway). Not to mention, they are not even functioning properly as area denial tool as they been intended to be. A simple pressure on spacebar keyboard button to activate bunnyhop can completely ignore whole area denial feature and laugh at it like it was just walking in the park (on this case, jumping), not to mention all those puddle of water on most pickup\ctf\etc, or those maps which have almost whole area with puddle of water like ff_waterpolo that completely negates the ground AoE 'area denial' feature of the nade.

Those napalm nades' power are FAR, FAR from more serious nades like MIRV and EMP, which I personally found far more overpowered and needed to be tweaked\changed, plus again, those nades almost completely necessary for the pyro to be viable class at high or just more serious level play, so it's really stupid and irrational to assume that napalm nades can be compared to all nades of other classes that have 2 max limit amount. Take a look at Quake 3 Fortress or Quake Team Fortress' napalm grenade, its far from a joke, but even pyro himself deals a really massive damage there unlike in Fortress Forever, yet can carry 4 max of those (3 max in Q3F, like rest of classes) without any balance issues.

If those napalm nades were as powerful as they are in Q3F and ETF with more serious range of ground area denial AoE and longer timer before it wears off, which cannot be ignored by simple bunnyhoping, deals far more serious and deadlier damage, and even itself deal more damage; or at least tweaked a lot to be at least properly working (or just functioning at all) as ground aoe true denial tool, stayed a little longer (maybe like a laser grenade or maybe even a little less), couldn't be ignored by simple bunnyhoping and didn't negates by not deep puddle and deal some noticeable damage like in last version of QTF, then it probably would be even fair to consider to limit them from 4 to 2 like rest of the classes have.

Currently class Pyro already suffers from many bugs and issues that hold him from it's full intended power, for example infamous and notorious hit registry issue of flamethrower, which makes pyro do not deal damage at all if the enemy is in corner, point black, under certain angle, or shoot any projectile based weapon which cancels flamethrower completely. This issue make pyro suffer big time in combat even against lesser health classes with faster speed and overall better movement like medic whose supernailgun can completely cancel the hit registry of flamethrower simple by shooting nailguns at pyro, even at close range flamethrower sometimes deals 0 damage to me, or even a scout in fair face to face combat situation which I often happened to kill pyros up close once they decide to simple rush me with flamethrower to death, resulting me to take damage only once or thrice only, sometimes cancel it completely. Incendiary Cannon hardly does any damage either (it ususally took me 6 direct hits with it to kill a single spy), whose DPS is questionable smaller than from "pellet gun", which resulting IC being not reliable weapon either and used only mostly for extra afterburn level. This is why afterburn damage is the only source of damage the Pyro can rely on, especially when fighting against heavy classes. Mostly just try your best to get close to the enemy, ignite him with all possible fire weapons, and then just support it with IC from safe distance so it does not extinguish over a time, this is how you mostly happen to kill a heavy class and have chance survive. Playing suicidal pyro and rush with flamethrower heavy classes such as soldier, hwguy or sentrygun supported by engineer will probably resulting in to fail anyway due not so high damage (plus awful hit registry) of constant burning flamethrower if both apponent had equal amount of skills on each side.

So this issue must be addressed first to be fixed before any changes would be even suggested toward overall stats of the class, especially in opposite direction of that class. Pyro hardly can use his primary weapons to win a fight against even midum armored classes such as demoman\medic\spy when both of the players have equal experience and skill in the game, and only have great rate of success against really light classes such as scout, sniper and sgless-empless engineer. However, if the flamethrower could pierce through projectiles and players like explosions of explosives do, that would probably fix the issue with hit registry, plus would make flamethrower hit multiple targets rather than one in it's range like real flamethrower could do when enemies are staying very close up to each other and flamethrower's theoretically can reach them both, while not doing any extra damage to single target. Pyro still would rely mostly on combination of afterburn level damage, but at least his primary weapons finally would get some proper use rather than be really situational ones, so he wouldn't feel so obligated to use all fire 3 weapons at once to be useful for team and serve as proper combat\assasination role of class, which will result less people will use all 3 fire weapons on every single enemy as the only way to deal good damage. Would be cool to give the class some real variety than feel like combinating all fire based weapons is the only one way to play as proper pyro. Afterall, for some of us it's just fun to take use primary weapon (flamethrower) as primary weapon and just burn someone with flames to death than cause annoyance with all those afterburn levels, even thought that would lack awesome and epic scream of death. Althrough, a whole tweak of flamethrower that would make him be more deadly against heavy classes would be really welcome, something like rampup damage that makes flamethrower do more damage after certain time for steady careful and correct aim for your targets while strafing and dodging, but don't do any higher damage at all to scouts and light classes. Would prevents those aimless "W+M1" and encourage pyro players to aim properly and carefully with flamethrower as well.

**Comment by MaxRideWizardLord** [comment]
Excuse me, but has been my old big message\comment actually posted on this topic?? I can't see it unless I'm registered. Would be sad if not.

But anyway - tl:dr: No No No and No. I'd love if it was opposite for him and he had more nades as they are the only source of decent damage against more solid enemies, or huge improvement for flamethrower for it to have ramp-up damage for hitting-over-time and ramp-up damage closer range, while at further\maximum range it would do less damage, plus fix it's bundle of bugs like being canceled by nailguns\projectiles and do no damage against enemies in corner.
