### ISSUE TITLE
Flag trails flick across the map when capturing the flag

### ISSUE THREAD

**Issue by AfterShockFF** [fortressforever/fortressforever#280]
I get a bit of a stutter on capture too, but that could be unrelated. (might be flaginfo icons updating or something)

**Comment by squeek502** [comment]
The stutter is definitely because of the flag trail whenever the flag moves across the map in an instant. Removing flag:StartTrail from base_teamplay **or** removing the `SetAbsOrigin( m_vStartOrigin );` line from `CFFInfoScript::CreateItemVPhysicsObject` removes the stutter.

Also, not sure why, but setting `cl_flagtrails 0` causes the stutter to become permanent when the flag moves across the map--it drops my framerate to 10 fps and stays there until I set `cl_flagtrails 1`.

This is all true when using debug dlls, unsure if anything changes with release dlls.
