### ISSUE TITLE
Bullet/flamethrower/etc traces are blocked by projectiles

### ISSUE THREAD

**Issue by squeek502** [fortressforever/fortressforever#291]
Split from #270. @MaxRideWizardLord said:

> Currently class Pyro already suffers from many bugs and issues that hold him from it's full intended power, for example infamous and notorious hit registry issue of flamethrower, which makes pyro do not deal damage at all if the enemy is in corner, point black, under certain angle, or shoot any projectile based weapon which cancels flamethrower completely.

**Comment by SergeantGrimes** [comment]
I really hope my idea will be taken under consideration to solve this. Perhaps along to that adding extra slightly more wider hitscan particles that would still able hit enemies, just so that they won't be as wide as actual flamethrower's flame hitbox but not as tiny as the invisible tiny hitscan particle. That way flamethrower won't lose it's width depth when dealing with enemies in very narrow places and corridors or if enemies abuse corners just to prevent flamethrower to do any damage to them. With extra slightly more wider hitscan particles you still be able to hit enemies while dodging them like maniac if they are abusing corner, just that you won't need perfect aim at their body with invisible straight perfect accurate hitscan particle the whole time of the process of fighting and dodging with no excusal for missing like you're using red pointer laser if the actual original flame's hitbox of flamethrower gone in a vain, this will as well save the immersion that you're using actual flamethrower weapon and not some blow torch.

**Comment by squeek502** [comment]
Confirmed that projectiles are blocking traces, and found that it affects many other weapons as well (AC most notably). Seems like something to do with collision groups or trace filters.

Relevant code:
- https://github.com/fortressforever/fortressforever/blob/beta/game_shared/gamerules.cpp#L702-L833
- https://github.com/fortressforever/fortressforever/blob/beta/game_shared/ff/ff_gamerules.cpp#L1963-L2046
- https://github.com/fortressforever/fortressforever/blob/beta/game_shared/util_shared.cpp#L292-L600
- https://github.com/fortressforever/fortressforever/blob/beta/public/bspflags.h
- https://github.com/fortressforever/fortressforever/blob/beta/public/const.h#L330-L361

Grenades use `COLLISION_GROUP_PROJECTILE`, while projectiles that collide with players (nails, rockets, etc) use `COLLISION_GROUP_ROCKET`
