### ISSUE TITLE
Nerf or remove the jump pad

### ISSUE THREAD

**Issue by mikeparker** [fortressforever/fortressforever#30]
I guess this might be too big an issue to raise here? But I think a lot of us have come to the conclusion that the jump pad has run it's course and has more of a detrimental effect on both pickup / competitive games (CTF) and pub games (making AvD stacked too much in offense favour).

**Comment by DexterHaslem** [comment]
a lot of us? I have to seriously ask because it's the first I've heard of it. but I dont really keep up on things and mostly just pub

**Comment by squeek502** [comment]
We've discussed it a few times on the dev forums:
- [The jumppad](http://forums.fortress-forever.com/showthread.php?t=19837)
- [The Jump Pad: Options](http://forums.fortress-forever.com/showthread.php?t=21501)

AfterShock's pros/cons list from 2009 (before jump pads were made team-oriented/destructable):

> Jumppad pros:
> - It enables new players to easily access the fast movement and aircontrol that is core to FF
> - It allows scouts to improve their team and speed others up, not just themselves
> - A small amount of strategy (?)
> - Enables heavier offy classes than before (?)
> 
> cons:
> - Makes medics much faster than before
> - doesnt appear to encourage heavy offy classes as much as we'd like (?)
> - Is quite overpowered for AvD maps as the whole team can use it all the time
> - Makes some front line defense positions near impossible to defend (e.g. monkey T)
> - Places much more emphasis on back line defense as front line is easier to get past

My current thoughts:

I think if we really want to attempt to solve the "competitive FF is offense-biased" problem, the jump pad really needs to be looked at, as I think it's a major contributor for ~~two~~ three reasons:
- It allows for near complete consistency in runs that would otherwise be somewhat difficult/special (for example, rampsliding the FD lip on schtop/monkey)
- It allows medics to pull off the above mentioned runs with the same exact consistency as scouts, even where it'd otherwise be impossible (medics wouldn't be able to achieve scout-level conc speeds without a jump pad).
- It allows for traversing some yards very quickly without the need of a conc, meaning that either 1) a conc is saved where it'd otherwise be used or 2) offense runs are much faster where players would otherwise bhop across the yard

Something I've thought about which could solve the second problem (but not the first, and only partially the third) would be to make the jump pad boost based on the speed of the class (meaning scout would get the highest boost, and HW would get the lowest). However, this is not a great solution, as it devalues other reasons for the jump pad existing and may not solve much in the long run.

Another tricky part of this: Is offense more fun _because_ of the consistency that the jump pad provides? I imagine that it is (at least partially), and it's something we've been dealing with for FF's entire lifetime: the players that have stuck with FF generally like the "easier" offense (me included), so it's tough to know what needs fixing and what is worth keeping.

**Comment by squeek502** [comment]
In reading through that "The jumppad" thread, there are some interesting ideas in it that I had completely forgotten about trying, namely the charge-to-use stuff.

Perhaps we could try a charge system again, doing something like:
- Starts charging whenever a player is inside the trigger (and loses charge when the trigger is empty)
- Whenever a player presses jump while inside the trigger, they get boosted based on the current charge level and the charge resets
- The time it takes to get a full boost is semi-significant (enough to make it a legitimate choice whether or not to use it in the yard in a competitive environment; meaning, it'd be slower overall, but would add consistency)

The problem would be that players could easily "steal" someone's charge (which is not really a trivial problem). Using an individual charge-level per player would avoid this problem, but might make it harder to communicate.

Just something to consider I guess.

EDIT: Relevant commits from when we tried a charge system:
41d7d899b9f65a0e1311a9aa8bfd0d51f141e5c3, 548e92190f115ef304a3a3db13be7010e35e7e51, 4fb0bce16379fc1533ced2e6535a07ad42b48e4e, 7109062956421efc94426aa25a2085d98e762a36, 3f995c5c629b050eb8f1efead4e04c0dad35702a and reverted in 209539f25d486f26a2c1b525cf83013bf39f0fb1

EDIT#2: A post that's worth reading:
http://forums.fortress-forever.com/showpost.php?p=444393&postcount=26

**Comment by DexterHaslem** [comment]
I was going to say why not just nerf velocity by like 20% or give it a cooldown :dancer:

**Comment by mikeparker** [comment]
#33 I have reduced the horizontal push, it still feels good as an instant gratification system but its much less overpowered now.

**Comment by FDA-** [comment]
After giving it some consideration, I'd be all for a complete removal or heavy nerf to jpads in terms of a comp setting. But I do think that'd be quite a slap to pubs. Demo, engi, and soldier are all very common O classes in the pub, with the occasional HW. Sometimes I just think about a brand new player taking ages to cross schtop yard just to get wrecked at FD. Obviously that wouldn't a problem if they took the time to educate themselves on the movement and subscribed to our idea of the classic OvD structure. But some players just don't really get into that, and I don't see why they should have to for general pub fun times. Jump pads facilitate that more casual and laid back play really well.

 I think it'd be nice to see a re-implementation that easily facilitated pub play, without being abused in comp.

**Comment by Largos** [comment]
"Another tricky part of this: Is offense more fun because of the consistency that the jump pad provides? I imagine that it is (at least partially), and it's something we've been dealing with for FF's entire lifetime: the players that have stuck with FF generally like the "easier" offense (me included), so it's tough to know what needs fixing and what is worth keeping."

I have to say yes, yes it is more fun.  monkey T is an odd example since it is located next to the fastest respawning health kit in the game.  

Pubbers will definitely feel this nerf and since none of them are reading this page now it will be simply confusing and infuriating.  I can see a small speed nerf but as it functions in most maps it just gets you to the action a little bit faster (and therefore lets you ahve more fun.)

**Comment by ddm999** [comment]
List of changes to jump-pad usage on AvD/IvD/CTF maps (as of 04/12/2014 - current FF Beta on Steam - with reduced vertical velocity and 768 horizontal speed):
- ff_2fort
  - Cannot JPad into conc from one battlement to another.
    - You **can** however just conc across.
  - Putting a JPad in the center of the bridge allows for you to just barely get into each base without hitting the ramp in and trimping.
  - Putting a JPad next to the water in the yard seems to be the best spot for it.
    - You no longer hit the roof and lose speed from going inside from this.
    - You can **just barely** get across the water without touching the bridge.
- ff_aardvark
  - Putting a JPad on the ledge out of spawn will **no longer** get you to the water.
    - Instead, you land on the rocky part that **will** slow you down if you land on it because it's slanted up.
  - JPad into conc off of this will get you about halfway through the other side's "lake".
  - Putting a JPad on the edge of the rocky section closest to your ledge seems to be the best place for it.
    - Notably, it's the only way to jump off the ledge without taking damage (because you hit the JPad before the floor, and land in the other team's "lake").
  - Using a JPad before you go into the speed booster does absolutely nothing. I don't actually know whether it did before, to be honest.
- ff_bases has no JPads.
- ff_cz2
  - Using a JPad from the right base exit won't send you into the wall if you try and go through the underpass to Cap 2 / 4. This also means you can carry more speed into the back entrance of Cap 3 (from a Scout having to restart bhopping to hit 500 u/s to maintaining speed at 600 u/s).
  - If you really want to get to the "island" that Cap 3 is on in one go (from right base exit), you'll have to either put your JPad close to the edge and jump right on that edge, or hop off the trim of the elevated spot (on the right) or the pathway (on the left).
  - The best usage of a JPad (for getting across the map) is to put it at the right side exit, and then hop on the left pathway before conc-ing and rampsliding up the right side ramp into/over Cap 3.
- ff_destroy
  - Putting a JPad in the normal spot now gets you to the very middle of the bridge.
    - Using a JPad into conc off of here still gets you to the top of the foyer if you hop off the top of the small enclosed passage holding the bridge.
  - And putting one on the bridge in the middle gets you to the normal JPad spot, but on the other team's side.
  - Putting one at the bottom of the small ramp up to battlements lets you rampslide up and either trimp over or hop around to the upper section.
    - You can't use a JPad from the actual yard to get to the upper section, however.
    - It's also possible to avoid hitting the bottom of the bridge by using a yard JPad as well.
- ff_dustbowl
  - Section 1 - Using a JPad at the lower attacker exit can't get you up to the upper section (on the left).
    - You can still get to the right side, but you will lose speed from tapping the edge of the cliff. In the worst case scenario, you may trimp off the ledge and lose your speed.
  - Section 1 - Using a JPad at the upper attacker exit is therefore an even better option now. You'll also land on terrain slanted downwards (on the upper left section), so you'll gain some more speed.
  - Section 1 - Using a JPad out of the far right building into the cap point area won't get you straight to the cap anymore.
  - Section 2 has no noticable changes. Of course you go less distance, but there are no jump spots.
  - Section 3 - Using a JPad at the top of the stairs around the corner from the cap point gets you across the bridge but not to the cap point itself.
  - Section 3 - You can't JPad out of the pit. I don't even know if you could do this before. :P 
- ff_ksour
  - Can no longer JPad and conc straight to 1st cap from archway (where the fence is during pre-game) - you still get close, though.
  - Can't rampslide up the cap 1 to cap 2 slope using a JPad.
  - A JPad on the Cap 1 Flag spawn will get you flying straight into the doorway on the building to Cap 2.
  - Can't rampslide up the slopes from cap 2 to cap 3 using a JPad.
    - Can't use this JPad into a conc to get up to the elevated spot above the archway between Cap 3 and the path to Cap 4.
  - Putting a JPad just after the archway between Cap 3 and the Cap 4 path still lets you trimp off the small slope onto the elevated area with the cap. (woo)
- ff_monkey
  - Yard JPads need to be at the edge of the bridge to be able to get extra speed off the downward slope of the other side of the bridge.
  - Enemy team FD JPads seem to be basically the same. If anything they're better because you don't have to try and slow down to get in the lower hallway from left FD anymore.
- ff_napoli
  - Section 1 - JPads right outside attacker door let you get into each doorway easier, but you **have** to hit the bridge if you don't want to go through one.
    - You also can't get onto the rooftop part in front of you from here.
  - Section 1 - JPads behind the next set of crates in front of attacker door **will** let you get onto this rooftop part, but it's still very difficult because you're only just above the lip when crouched (you **have** to crouch or you'll hit the lip).
  - No real changes to Section 2 or 3 at all (you go less distance, but there's no changes to places you can get to I believe).
- ff_openfire
  - A JPad designed for getting to the battlements **must** be placed 3/4ths of the way along the bridge instead of in the middle.
    - Using this JPad can no longer send you flying **through** the window, you **have** to hit the sloped part with the team logo in.
  - Putting a JPad in the water entrance will only get you to right before the ramp up into the flag room.
- ff_palermo
  - Putting a JPad inside the tunnel exit from attacker spawn won't get you over the wall and over the water anymore.
    - Instead, put it just outside the tunnel and you'll just reach the other side.
    - JPad into conc doesn't get you near the cap, instead you'll go less distance than a regular hh conc.
  - A JPad right before the ramp (to the right of CP1) won't get you to the stairs anymore.
    - A JPad at the top of this ramp gets you up the stairs, but doesn't give you enough height or speed to go any further.
  - Cap 2 spots are unaffected.
  - Using a JPad that's at the bottom of the tunnel ramp going to CP 3 will make you just tap the upper edge of the ramp.
    - This **will** disable the JPad conc speed limit (so you can conc at full speed through the tunnel).
  - Cap 4 spots are unaffected.
- ff_schtop
  - You can barely get around the corner using a JPad that's on the glowing square.
    - You land on the short straight bridge section between the actual corner of the bridge and the middle section.
  - Putting a JPad just on the bridge at the left side makes you **just** able to reach the middle section (but you'll have to really stick to the edge to avoid trimping).
    - This means JPad's can't really be comboed through the yard anymore.
    - If you are going to combo JPad's, I'd recommend putting one in the front door archway, followed by one in the very middle of the corner, followed by one in the very middle of the center section.
    - The issue with this comboing is that using the first JPad to get into your base to capture **will always** make you hit the walkway from upper yard.
  - No matter where your JPad is, you'll still be able to JPad conc up to the upper yard.
- ff_shutdown2
  - You can rampslide up the center section ramp from a JPad right outside fd.
    - Only if you're lucky.
    - Most of the time you'll trimp, but unlike with the old JPad you get barely any vertical speed so you probably won't take fall damage.
  - I'd recommend putting a JPad just before the metal part of the center section ramp.
    - Make sure to put it from **on** the ramp or it'll collide with the ground, fly into the air and go back quite far.
  - No real changes to JPads on the underground tracks.
- ff_well
  - To get onto the top of the center section you'll need to put your JPad on the curved slant of the river bridge instead of straight in front of fd.

**Comment by squeek502** [comment]
Resolved by #122
