### ISSUE TITLE
Master Server is Inaccessible

### ISSUE THREAD

**Issue by ax-rwnd** [fortressforever/fortressforever#332]
Since some week ago I have been unable to retrieve the server list from the master server. From the people I've met sporadically on servers, it seems other players are having the same issue.

I haven't seen any posts addressing it on the forum and I can't create a post regarding it due to insufficient privileges (never got the confirmation mail). Perhaps some light could be brought to the issue and then a fix could be proposed?

**Steps to reproduce:**
* Launch Fortress Forever
* Open the server browser.
* Await the timeout.

**Comment by doublah** [comment]
**Relevant:**
[Steam Discussions - Whelp, the master server is dead now.](http://steamcommunity.com/app/253530/discussions/0/217690940939391973/)
[Steam Discussions - Why is the Master Server down?](http://steamcommunity.com/app/253530/discussions/0/217691032433688469/)

**My responses:**
"Pretty sure Steam/Valve host the master servers for source games which are on steam but I might be wrong."
"As far as I know Valve host(ed) the Master Server, going to try and contact them and see if killing them was deliberate.
Side note: The master server for Neotokyo, which also runs on Source 2006 (the same engine as FF) is also down."
"My guess is Valve killed off the servers for Source 2006 games, as all their Source games have been ported to newer versions of the Source engine."

**Also, known workarounds:**
**1.** Steam Client Server Browser (Steam > View > Servers > Change Filters > Game > Fortress Forever).
**2.** Adding server IPs to 'Favorites' in game and using that in the server browser.
**3.** Using third party services like [gametracker](http://www.gametracker.com/search/ff/).

As of now, I've still received no response from Valve on this matter, maybe if a dev tried to bring it up with Valve we'd get some answers.
But basically for now, FF is dead. I can't imagine many new players bothering to go out of the way to play it.

**Comment by BullyFF** [comment]
Servers are listing fine for me:

Suzys 64.94.100.40:27015
East coast 66.150.121.200:27015
Motos 74.91.114.247:27015
Boneyard 64.94.238.27:27015
Anitalink 193.124.184.251:27066
MaxFF 95.172.92.117:27018
TFC-R 176.31.182.154:27115
Travincial 74.91.124.57:27015
#ff.pickup 104.153.105.186:27015

Hope this helps

**Comment by ax-rwnd** [comment]
It's still broken for me and very few new players will be joining a game with no master server, as was mentioned previously.

@BullyFF what's the content of your _Fortress Forever/platform/config/masterserver.vdf_? Perhaps we're connecting to different master servers and the one we're trying has gone down without a maintainer.

**Comment by BullyFF** [comment]
In game nothing shows up but if you bring servers window up direct from steam it lists OK here.

my master servers are:
208.64.200.39:27011
208.64.200.52:27011
208.64.200.65:27015

**Comment by psychonic** [comment]
@BullyFF Valve is aware of the issue and working on a proper fix. In the meantime, I have a hacked up fix that I just pushed for NEOTOKYO which is also on the Source 2006 engine.

Replacing the steam.dll in the root folder with this one will cause the new master server address to be returned by the old Steam servers API. (Which is where it's currently getting those addresses that no longer work).
https://users.alliedmods.net/~psychonic/steam.dll

Then, add this masterservers.vdf to platform/config/ so that it overwrites the cache for anyone that still has the old ones in there (else they'd have to manually edit or delete theirs, or wait until the file time expires).
https://users.alliedmods.net/~psychonic/masterservers.vdf

**Comment by squeek502** [comment]
Thank you @psychonic, you're the best.

**Comment by doublah** [comment]
Not dead yet.

**Comment by squeek502** [comment]
Fixed build should be live.

**Comment by psychonic** [comment]
@squeek502 Looks like they changed back to the old IPs. Easiest fix is to just delete steam.dll and platform/config/MasterServers.vdf. For the former, it will fall back to the Steam Client's steam.dll (which can also be updated by Valve in the future), and for the latter, it will get regenerated automatically from the dll as it's just a cache.

FWIW, I had trouble getting MasterServers.vdf deleted from the depot, but can also just change it to be empty.

    "MasterServers"
    {
    }

Edit: My issue with MasterServers.vdf was due to a long-forgotten `"FileExclusion"	"platform\config\*"` in the depot script.

**Comment by squeek502** [comment]
Thanks again @psychonic, you continue to be the best. Pushing a fixed build now.

**Comment by pike2hc** [comment]
This issue has come up again.

It's been about a week now that the in game server list shows no servers.

**Comment by squeek502** [comment]
@psychonic provided a fix for us again, will get it released soon.

**Comment by squeek502** [comment]
Fixed build pushed to Steam, should work again once your FF updates.

**Comment by doublah** [comment]
Was this Valve's doing again?

**Comment by squeek502** [comment]
Yeah, the 2006 SDK is basically completely unsupported at this point and anything that breaks is extremely unlikely to be fixed. @psychonic's fix was to make the 2006 SDK work with the 2007 server browser.
