### ISSUE TITLE
Fix default config file

### ISSUE THREAD

**Issue by mikeparker** [fortressforever/fortressforever#4]
Stuff like:
- Default crosshair sucks and is too big
- hud_fastswitch 0 is also bad

probably other issues worth looking at

**Comment by hlstriker** [comment]
Maybe we should set a default crosshair for each weapon.

**Comment by alaswell** [comment]
I think we should definitely find a better default one at the least, but one for every class would be kinda cool and help newb's to understand they can customize per class/weapon.

**Comment by alaswell** [comment]
So I played with this a bit today and have a couple of things:

1) I created a new issue #43 because the crosshair stuff isn't in the default_config.cfg it's in another file.

2) I think we should change a couple of things:

a) I think we should update the WhenFFWillOut name stuff, either remove it completely or update it at least. The game has been out for years and no one is going to understand that joke anymore anyway...

b) I think we need to add 
con_enable 1 
hud_fastswitch 1 

We already bind ` to be console so why would it not be enabled to start with? 
The fastswitch is better, it makes more since and is easier than hitting mouse again.

c) We bind a lot of stuff twice, is that necessary? If not its a simple fix too:
bind "`"        "toggleconsole"
bind "~"        "toggleconsole" (literally the same key, I don't think caplock matters?)

bind "ALT"      "+speed"
bind "SHIFT"        "+speed" (walk is bound twice...I personally think SHIFT should get allocated to something better than walk? Maybe +voicerecord?)

bind "b"        "changeclass"
bind "n"        "changeteam"
bind "."        "changeteam"
bind ","        "changeclass" (again doubled, not sure why?)

**Comment by squeek502** [comment]
- `con_enable 1` was made default last patch
- Still unsure about `hud_fastswitch 1`. It seems obvious to want it enabled for serious play, but I think it might be helpful when you're brand new. Not sure how to determine whether or not its worth keeping disabled by default
- The console bind has been set like that for as long as I can remember (it's even set like that in the default TFC config). Not sure why the others are duplicated, but it doesn't seem like a bad thing. HL2 allows for alternate keys and both binds will show up in the key config, so it's not like it's a hidden feature.

**Comment by squeek502** [comment]
Done by #90. Crosshair stuff moved to #43
